### ISSUE TITLE
Message tellling why the tools falls back in interactive mode

### ISSUE THREAD

**Issue by lmichel** [ivoa/mivot-validator#8]
The following command
```
mivot-snippet-instance coords:TimeSys `pwd` coords.TimeSys.example \
  -cc dmrole=coords:TimeFrame.refDirection,context=coords:TimeSys,dmtype=coords:RefLocation,class=coords:StdRefLocation \
  -cc dmrole=coords:TimeFrame.refPosition,context=coords:TimeSys,dmtype=coords:RefLocation,class=coords:LonLatPoint
```
Suggests to use an instance of `coords:LonLatPoint`as concrete class of `coords:RefLocation`.
This makes no sense and the tool ignore that parameter and switch in interactive mode, for that case. This is good.

However, it would be nice to have a little message telling the reason why the tool falls backs in interactive mode.

Something like `No  (or a wrong) concrete class found in the command line`

**Comment by Lienub** [comment]
see f1a6c3c220be49ef3fa7112e3cbd5161f6436315
